import defaultTpl from './fullstreet/default.html';
import frTpl from './fullstreet/fr.html';

var templates = {
    default: defaultTpl,
    de: defaultTpl,
    at: defaultTpl,
    fr: frTpl,
    us: frTpl,
    dz: frTpl,
    ad: frTpl,
    az: frTpl,
    am: frTpl,
    au: frTpl,
    bh: frTpl,
    bd: frTpl,
    bn: frTpl,
    kh: frTpl,
    ca: frTpl,
    cn: frTpl,
    cx: frTpl,
    cc: frTpl,
    cd: frTpl,
    cg: frTpl,
    ck: frTpl,
    cy: frTpl,
    ci: frTpl,
    dm: frTpl,
    eg: frTpl,
    fj: frTpl,
    ga: frTpl,
    gm: frTpl,
    ge: frTpl,
    gh: frTpl,
    gi: frTpl,
    gp: frTpl,
    gu: frTpl,
    gy: frTpl,
    hk: frTpl,
    in: frTpl,
    id: frTpl,
    ie: frTpl,
    gb: frTpl,
    il: frTpl,
    la: frTpl,
    lb: frTpl,
    lu: frTpl,
    mr: frTpl,
    mu: frTpl,
    mc: frTpl,
    ms: frTpl,
    ma: frTpl,
    mm: frTpl,
    na: frTpl,
    nz: frTpl,
    ng: frTpl,
    nf: frTpl,
    om: frTpl,
    pk: frTpl,
    pw: frTpl,
    ph: frTpl,
    pr: frTpl,
    rw: frTpl,
    re: frTpl,
    bl: frTpl,
    sh: frTpl,
    kn: frTpl,
    mf: frTpl,
    sa: frTpl,
    sn: frTpl,
    sl: frTpl,
    sg: frTpl,
    tw: frTpl,
    tz: frTpl,
    th: frTpl,
    tg: frTpl,
    tt: frTpl,
    tn: frTpl,
    tm: frTpl,
    tc: frTpl,
    vm: frTpl,
    wf: frTpl,
    ye: frTpl,
    zm: frTpl,
    zw: frTpl,
    getTemplate: function(countryCode) {
        countryCode = countryCode.toLowerCase();
        if(!!this[countryCode]) {
            return this[countryCode];
        } else {
            return this.default;
        }
    }
}

export default templates
